### PR TITLE
chore: Delete useless file

### PR DESCRIPTION
**Pull request by myml**
Fixes https://github.com/linuxdeepin/developer-center/issues/3005

delete useless file

### CODE REVIEW

**Comment by BLumia** [comment]
编辑器项目还没迁移到 github，恐怕要迁移完才能合入了= =

**Comment by starhcq** [comment]
deepin-editor project was successfully migrated to Github. You can submit a PR request to us. Best wishes.

**Comment by myml** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Review by BLumia — APPROVED** [review]

**Pull request merged**
